### ISSUE TITLE
Dependencies Installed

### ISSUE THREAD

**Issue by RehaniH** [RehaniH/FashionStore#1]
Hi guys, 
This issue is opened so that we can keep track of the dependencies added to the project by each contributor. For adding dependencies to the front-end project first change the directory to the front-end folder and then add the dependency. 

The added dependencies are as follows:

front-end: 
     bootstrap
     react-router-dom

back-end:  
     express
     mongoose
     body-parser
    cors

**Comment by RehaniH** [comment]
Front-end : react-calendar

**Comment by shanesoysa** [comment]
front end =>
material-ui/core
react-moment
react-icons
